# Generated by Django 3.0.2 on 2020-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLASI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year1', models.CharField(max_length=4)),
                ('school_year2', models.CharField(max_length=4)),
                ('lrn', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('returning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('grade_level_to_enroll', models.CharField(max_length=50)),
                ('last_grade_level_com', models.CharField(max_length=50)),
                ('last_school_year_com', models.CharField(max_length=20)),
                ('last_school_attended', models.CharField(max_length=200)),
                ('school_id', models.CharField(max_length=50)),
                ('school_address', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=8)),
                ('school_to_enroll_in', models.CharField(max_length=200)),
                ('school_id_to_enroll', models.CharField(max_length=50)),
                ('school_address_to_enroll', models.CharField(max_length=200)),
                ('semester', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], max_length=4)),
                ('track', models.CharField(choices=[('Accountancy, Business and Management', 'ABM'), ('Humanities and Social Sciences', 'HUMSS'), ('Science, Technology, Engineering, and Mathematics', 'STEM'), ('General Academic Strand', 'GAS')], max_length=100)),
                ('strand', models.CharField(choices=[('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood'), ('Sports Track', 'Sports Track'), ('Arts and Design Track', 'Arts and Design Track')], max_length=100)),
            ],
        ),
    ]
