# Generated by Django 3.0.2 on 2020-05-22 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psa_cer_no', models.CharField(max_length=50)),
                ('lrn', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('extension_name', models.CharField(max_length=50)),
                ('birthdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('ip', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('ip_specify', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('special_ed_needs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('speed_needs_specify', models.CharField(max_length=50)),
                ('technology_devices', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('technology_devices_specify', models.CharField(max_length=50)),
                ('house_number_and_street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='glasi',
            old_name='lrn',
            new_name='wlrn',
        ),
        migrations.AddField(
            model_name='glasi',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stem.STUDENT_INFO'),
            preserve_default=False,
        ),
    ]
