# Generated by Django 3.0.2 on 2020-05-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0002_auto_20200522_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='PARENT_GUARDIAN_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_educ_attainment', models.CharField(choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50)),
                ('father_employment_status', models.CharField(max_length=50)),
                ('father_working_from_home_due_to_ecq', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('father_contact', models.CharField(max_length=13)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_educ_attainment', models.CharField(choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50)),
                ('mother_employment_status', models.CharField(max_length=50)),
                ('mother_working_from_home_due_to_ecq', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mother_contact', models.CharField(max_length=13)),
                ('guardian_full_name', models.CharField(max_length=100)),
                ('guardian_educ_attainment', models.CharField(choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50)),
                ('guardian_employment_status', models.CharField(max_length=50)),
                ('guardian_working_from_home_due_to_ecq', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('guardian_contact', models.CharField(max_length=13)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.STUDENT_INFO')),
            ],
        ),
    ]
