# Generated by Django 3.0.2 on 2020-05-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0003_parent_guardian_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_guardian_info',
            name='student',
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_educ_attainment',
            field=models.CharField(blank=True, choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='father_working_from_home_due_to_ecq',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='grade_level_to_enroll',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='guardian_educ_attainment',
            field=models.CharField(blank=True, choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='guardian_employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='guardian_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='guardian_working_from_home_due_to_ecq',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='last_grade_level_com',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='last_school_attended',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='last_school_year_com',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_educ_attainment',
            field=models.CharField(blank=True, choices=[('Elementary Graduate', 'Elementary Graduate'), ('High School Graduate', 'High School Graduate'), ('College Graduate', 'College Graduate'), ('Vocational', 'Vocational'), ('Masters/Doctorate degree', 'Masters/Doctorate degree'), ('Did not attend school', 'Did not attend school')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='mother_working_from_home_due_to_ecq',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='returning',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_address_to_enroll',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_id_to_enroll',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_to_enroll_in',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_year1',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='school_year2',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='strand',
            field=models.CharField(choices=[('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood'), ('Sports Track', 'Sports Track'), ('Arts and Design Track', 'Arts and Design Track')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_info',
            name='track',
            field=models.CharField(blank=True, choices=[('Accountancy, Business and Management', 'ABM'), ('Humanities and Social Sciences', 'HUMSS'), ('Science, Technology, Engineering, and Mathematics', 'STEM'), ('General Academic Strand', 'GAS')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='wlrn',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_info',
            name='extension_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='house_number_and_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='ip',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='ip_specify',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='special_ed_needs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='speed_needs_specify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='technology_devices',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='technology_devices_specify',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='GLASI',
        ),
        migrations.DeleteModel(
            name='PARENT_GUARDIAN_INFO',
        ),
    ]
