# Generated by Django 3.0.2 on 2020-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0004_auto_20200522_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='psa_cer_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
