# Generated by Django 3.0.2 on 2020-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0005_auto_20200523_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='birth_certificate',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='birth_certificate'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='form_137',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='form_137'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='student_pics'),
        ),
    ]
