# Generated by Django 3.0.2 on 2020-05-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0006_auto_20200523_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='strand',
            field=models.CharField(choices=[('Accountancy, Business and Management', 'ABM'), ('Humanities and Social Sciences', 'HUMSS'), ('Science, Technology, Engineering, and Mathematics', 'STEM'), ('General Academic Strand', 'GAS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='track',
            field=models.CharField(blank=True, choices=[('', ''), ('Academic Track', 'Academic Track'), ('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood'), ('Sports Track', 'Sports Track'), ('Arts and Design Track', 'Arts and Design Track')], max_length=100, null=True),
        ),
    ]
