# Generated by Django 3.0.2 on 2020-05-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0008_auto_20200523_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='birth_certificate',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='birth_certificate'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='form_137',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='form_137'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='student_pics'),
        ),
    ]
